start complete
Initiating game:  PandaReach-v3
Experiments starting for:  23
Task Name:  CustomReachEnv1
Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 162, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 179, in run
    self.take_step()
  File "/home/user/Thesis/trial.py", line 359, in take_step
    envState = self.agent.step(self.humanAction, self.humanFeedback)
  File "/home/user/Thesis/agent.py", line 386, in step
    self.Qagent.qtable.to_csv(str(self.user_experiment_path)+"/"+self.gameName+"/"+self.taskName+"_Qtable"+".csv")
  File "/home/user/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Thesis/userdata/PandaReach-v3/23/PandaReach-v3/CustomReachEnv1_Qtable.csv'
Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 162, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 179, in run
    self.take_step()
  File "/home/user/Thesis/trial.py", line 359, in take_step
    envState = self.agent.step(self.humanAction, self.humanFeedback)
  File "/home/user/Thesis/agent.py", line 386, in step
    self.Qagent.qtable.to_csv(str(self.user_experiment_path)+"/"+self.gameName+"/"+self.taskName+"_Qtable"+".csv")
  File "/home/user/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/home/user/.local/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Thesis/userdata/PandaReach-v3/23/PandaReach-v3/CustomReachEnv1_Qtable.csv'