start complete
Initiating game:  PandaReach-v3
Experiments starting for:  0
Task Name:  CustomReachEnv0
[34m[1mwandb[39m[22m: Network error resolved after 0:00:17.028939, resuming normal operation.
done
{'upload': {'projectId': None, 'participantID': '0', 'file': 'trial_0', 'path': './Trials/trial_0'}}
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 165, in controlBehaviour
    def controlBehaviour(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 165, in controlBehaviour
    def controlBehaviour(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'