Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 124, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 131, in run
    self.reset()
  File "/home/user/Thesis/trial.py", line 163, in reset
    self.create_file()
  File "/home/user/Thesis/trial.py", line 379, in create_file
    self.outfile = open(path, 'ab')
FileNotFoundError: [Errno 2] No such file or directory: './Trials/trial_Con - Testing 1'
Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 124, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 131, in run
    self.reset()
  File "/home/user/Thesis/trial.py", line 163, in reset
    self.create_file()
  File "/home/user/Thesis/trial.py", line 379, in create_file
    self.outfile = open(path, 'ab')
FileNotFoundError: [Errno 2] No such file or directory: './Trials/trial_Con - Testing 1'
